---
sudo: false

cache:
  directories:
    - node_modules
    - bower_components

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - build-essential
            - clang-3.3
            - fakeroot
            - git
            - libgnome-keyring-dev
            - rpm
            - libx11-dev
            - libxkbfile-dev
      env:
        - NODE_VERSION=6.3 DISPLAY=:99.0 CC=clang CXX=clang++ npm_config_clang=1 TARGET_ARCH=x64 OS=LINUX
    - os: osx
      osx_image: xcode7.3
      env:
        - NODE_VERSION=6.3 TARGET_ARCH=x64 OS=DARWIN DISPLAY=:99.0

before_install:
  # OS X ---------------------------------------------------------------------
  # nvm is not yet supported on osx, manually install
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version && npm --version
  # Continue with our normally scheduled program -----------------------------
  - "npm config set spin false"
  - "npm install -g node-gyp"
  - "npm install -g grunt-cli"
  - "npm install -g bower"

install:
  - npm install
  - bower install
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm test

after_success:
  # Todo: Fix this
  # Report code coverage
  # - node ./node_modules/.bin/codecov
