---
sudo: false

cache:
  directories:
    - node_modules
    - bower_components

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - xvfb
          - libgnome-keyring-dev
          - g++-4.8
      env:
        - NODE_VERSION=6.3 TARGET_ARCH=x64 OS=LINUX
    - os: osx
      osx_image: xcode7
      env:
        - NODE_VERSION=6.3 TARGET_ARCH=x64 OS=DARWIN

before_install:
  # OS X ---------------------------------------------------------------------
  # nvm is not yet supported on osx, manually install
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version && npm --version
  # LINUX --------------------------------------------------------------------
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CXX=g++-4.8; fi
  # Continue with our normally scheduled program -----------------------------
  - "npm config set spin false"
  - "npm install -g node-gyp"
  - "npm install -g grunt-cli"
  - "npm install -g bower"

install:
  - npm install
  - bower install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm run rebuild

script:
  - npm test

after_success:
  # Todo: Fix this
  # Report code coverage
  # - node ./node_modules/.bin/codecov
